### PR TITLE
Update kotlin to 1.6.10

### PR DESCRIPTION
**Pull request by deathcoder**
closes https://github.com/aboutyou/dart_packages/issues/271

### CODE REVIEW

**Comment by tp** [comment]
@deathcoder Should we treat this as a breaking change? Meaning if one has ones local project setup to Kotlin `1.3.*` (the default with Flutter 2.5?), will this cause problems when one would update to the latest package with this?

(Currently OOO, but can try this out locally later today.)

**Comment by tp** [comment]
Okay, so the failing CI build seems to answer my previous question.

Then I suppose we'll have to bump the CI build to the point to the upcoming Flutter version, release the plugin with a breaking change and bump the Flutter minimum version in the `pubspec.yaml`.

**Comment by HenriBeck** [comment]
@tp I would suggest only bumping the version officially once the Flutter version is also released to the stable channel.

For now, we could pull in this change into one of our branches, and then for anyone to use it, they would have to point to an exact commit

**Comment by HenriBeck** [comment]
@tp @deathcoder I pulled in the change in our repository (#275) and let's continue the change once Flutter 2.9 is released.

**Pull request closed without merging**
