### PR TITLE
Fix build with Xcode 13

### PR DESCRIPTION
**Pull request by tp**
Extends https://github.com/aboutyou/dart_packages/pull/221 to work on both Xcode 12 and 13.

Also adds a new CI build for Flutter 2 and both Xcode versions for the SiwA plugin.

### CODE REVIEW

**Comment by HenriBeck** [comment]
@tp I will have a look here in the evening.

**Review by HenriBeck — APPROVED** [review]

**Comment by HenriBeck** [comment]
@tp changes look good; I will quickly pull them into our App and double-check that a successful login is still possible.

**Comment by SarvagyaVaish** [comment]
@HenriBeck Thanks so much for helping fix this issue :) 
Issue #213 references commit 3d2633761b8cdb04d2816a5f079be765bdcb7603 to use while this issue is being resolved. That doesn't seem to exist anymore because I'm guessing the branch was force pushed to. Is there a new commit you suggest using for now?

**Comment by HenriBeck** [comment]
@SarvagyaVaish thanks for letting me know, I added a new comment here: https://github.com/aboutyou/dart_packages/issues/213#issuecomment-924233155

**Comment by SarvagyaVaish** [comment]
@HenriBeck sorry for the newbie question - what happens next? should we continue to use the workaround till a new version gets released to pub.dev?

**Comment by yusriltakeuchi** [comment]
How to use this merge in my app?

**Comment by SarvagyaVaish** [comment]
> How to use this merge in my app?

In the Podfile add the following:
```
sign_in_with_apple:
  git:
    url: git://github.com/aboutyou/dart_packages.git
    ref: master
    path: packages/sign_in_with_apple

```

**Comment by yusriltakeuchi** [comment]
> > How to use this merge in my app?
> 
> In the Podfile add the following:
> 
> ```
> sign_in_with_apple:
>   git:
>     url: git://github.com/aboutyou/dart_packages.git
>     ref: master
>     path: packages/sign_in_with_apple
> ```

Thank youu

**Pull request merged**
