### PR TITLE
Added missing null checkers

### PR DESCRIPTION
**Pull request by HugoSart**
Related to #125

### CODE REVIEW

**Comment by HenriBeck** [comment]
@HugoSart thanks for the quick fix. Could you please quickly provide the flutter version you are on and the kotlin version to see when this breaks.

**Comment by HugoSart** [comment]
@HenriBeck sure.
Flutter: 1.20.1
Kotlin: 1.3

**Comment by HenriBeck** [comment]
@HugoSart could you maybe provide a repository where this issue appears? 

I created a new flutter project with version 1.20 and there the compilation works. 
Also upgrading our example app to flutter 1.20.1 and it runs on android without problems.

**Comment by HugoSart** [comment]
@HenriBeck unfortunately I was not able to reproduce this problem by starting from a fresh project.

I created a new project, copied the pubspec.yml, and both build.gradle from the broken project to the working one, but the problem did not happen. I'm exploring it more trying to find the reason.

OBS: I should've mentioned it before, but this problem only happens when building with --release option.

**Comment by HenriBeck** [comment]
@HugoSart does this maybe happen with some special android sdk version? Either the minSdkVersion or targetSdkVersion?

**Comment by hespinola** [comment]
I'm having this exact same problem.

Flutter version 1.20.4
Android minSdkVersion 21
Android targetSdkVersion 29
Kotlin version 1.4.10

**Comment by HugoSart** [comment]
This was some time ago, and as I remember, the solution was to add these lines to the root build.gradle:
```
buildscript {
    ext.kotlin_version = '1.3.72'
    // other definitions ...

    dependencies {
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
       // other definitions ...
    }

}
```
So, basically, I set the kotlin version to 1.3.72. As I said, this is what I remember, maybe I did something else too, but you could give it a try @hespinola .

**Comment by wahyubucil** [comment]
I'm having the same problem. Changing the Kotlin version to 1.3.72 doesn't help

Flutter version 1.22.1
Android minSdkVersion 21
Android targetSdkVersion 29
Kotlin version 1.3.72

**Comment by hespinola** [comment]
> I'm having the same problem. Changing the Kotlin version to 1.3.72 doesn't help
> 
> Flutter version 1.22.1
> Android minSdkVersion 21
> Android targetSdkVersion 29
> Kotlin version 1.3.72

These are my currently working settings:

targetSdkVersion 30
Kotlin version 1.3.50

Then inside build.gradle:

classpath 'com.android.tools.build:gradle:3.6.4'

And in gradle-wrapper.properties:

distributionUrl=https\://services.gradle.org/distributions/gradle-5.6.4-all.zip

**Comment by wahyubucil** [comment]
@hespinola The problem still exists. I already use those settings

I check the `SignInWithApplePlugin.kt` on Android Studio. And it shows error too. So I think we need to merge this PR

**Comment by yswtrue** [comment]
Same issue

**Comment by hespinola** [comment]
I can confirm the problem still exists, I mentioned it worked in my previous comment but I didn't realize I was using the forked version with the fix.

@tp @HenriBeck  If this PR solves the issue and doesn't seem to break the code I don't see why it wouldn't be merged.

**Comment by HenriBeck** [comment]
@hespinola we will have a look at this now that this affects more people.

**Comment by tp** [comment]
@hespinola You're right in that this seems harmless, but we also want to find out the reason for this to maintain it properly in the future.

After upgrading to 

* `ext.kotlin_version = '1.4.10'`
* `classpath 'com.android.tools.build:gradle:3.6.4'`
* `distributionUrl=https\://services.gradle.org/distributions/gradle-5.6.4-all.zip` 

I did not run into any build issues with `sign_in_with_apple` 2.5.2 using `release` builds in CI.

So I think there is some other difference between the projects that run into this issue and those who don't.

**Comment by tp** [comment]
I found the way to run into this issue:

Setting `compileSdkVersion 29` in `packages/sign_in_with_apple/android/build.gradle`.

Which would make sense if the nullability annotations where updated in that one.

My assumption is that somehow this gets overwritten for some projects, but not others, hence only few run into this. 

Anyway, I tried @HugoSart's fix locally in the then failing example project, and this indeed fixed the issue.

Will release an update shortly.

**Review by tp — APPROVED** [review]

**Comment by tp** [comment]
Thanks @HugoSart & @hespinola for your sustained effort in getting this fixed :)

**Pull request merged**
